config-version: 2

name: 'crm_warehouse'
version: '1.0.0'
profile: 'crm_warehouse'

model-paths: ["crm_warehouse/models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  crm_warehouse:
    +schema: crm_warehouse_transformed
    +materialized: view
    dim_customers:
      +enabled: true
    dim_products:
      +enabled: true
    dim_tickets:
      +enabled: true
    fact_sales:
      +enabled: true
    fact_support_ticket:
      +enabled: true
