name: 'crm_warehouse'
version: '1.0.0'
profile: 'crm_warehouse'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  crm_warehouse:
    example:
      +materialized: view
    +schema: crm_warehouse_transformed  # all dbt-managed models go here
